
/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class ShiroSecurityFilters {

    def filters = {
        all(controller:'*', action:'*') {
            before = {
                
                // Ignore direct views (e.g. the default main index page).
                if (!controllerName || controllerName == 'assets') return true
                accessControl();
            }
        }
    }
}
